---

os:
  - linux
  - osx

dist: trusty
sudo: required

cache:
  directories:
    - .bundle/gems

language: ruby

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      brew update;
      brew install shellcheck clang-format@3.8;
      ln -s /usr/local/opt/clang-format@3.8/bin/clang-format /usr/local/bin/clang-format;
      if [ "$LIBEDIT" == "true" ]; then
        brew install libedit;
      fi
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install shellcheck;
      if [ "$LIBEDIT" == "true" ]; then
        sudo apt-get install libedit-dev;
      fi
    fi

install:
  - if [ "$LIBEDIT" == "true" ]; then
      rvm reinstall "$TRAVIS_RUBY_VERSION" --configure --enable-libedit
                                           --rubygems ignore;
    fi

before_script:
  - git config --local user.email 'travis@travis.ci'
  - git config --local user.name 'Travis CI'

script:
  - script/ci.sh
  - bundle exec codeclimate-test-reporter || test true

rvm:
  - 2.2.8
  - 2.2.8-clang
  - 2.3.5
  - 2.3.5-clang
  - 2.4.2
  - 2.4.2-clang
  - ruby-head
  - ruby-head-clang

matrix:
  fast_finish: true

  allow_failures:
    - rvm: ruby-head
    - rvm: ruby-head-clang

  exclude:
    - os: osx
      rvm: 2.2.8-clang
    - os: osx
      rvm: 2.3.5-clang
    - os: osx
      rvm: 2.4.2-clang
    - os: osx
      rvm: ruby-head-clang

env:
  matrix:
    - "LIBEDIT=true"
    - "LIBEDIT=false"

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  code_climate:
    repo_token: 02530029b1e956220f05076c590b84b9ab078362c9083312eb2ad41cab138408
